apiVersion: skaffold/v2beta24
kind: Config

build:
  artifacts:
  - image: carl1984a0/m-client-0
    context: client
    sync:
      manual:
      - src: '**/*.css'
        dest: .
      - src: '**/*.html'
        dest: .
      - src: '**/*.js'
        dest: .
    docker:
      dockerfile: Dockerfile.dev
  local:
    push: false
    useBuildkit: false
deploy:
  kubectl:
    manifests:
    - k8s/client-deployment.yaml
portForward:
- resourceType: deployment
  resourceName: client-deployment
  port: 3000
